using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using VoidDay.Balance.Schema;
using VoidDay.Core.Model;

namespace VoidDay.Balance.Unity;

/// Writes an edited BalanceConfig back into the Unity `.asset` files it came from — surgically.
///
/// The one rule that governs everything here: **never reserialize.** A one-field change must produce
/// a one-line `git diff`. So the writer resolves each changed value to the exact line in the exact
/// asset and replaces only the scalar after the colon; every other byte is left untouched. A
/// YamlDotNet round-trip would reformat whole files and make the diff unreviewable — that is the
/// milestone's whole point (minimal diff is a correctness property, not a nicety).
///
/// It supports: editing line-addressable top-level scalars; inserting a new RecipeSO (asset + .meta
/// + a reference appended to its owning StationSO); positional edits to the Levels asset (xpThreshold
/// + grant amounts) and full regeneration of a level's grant list when its structure changes (grant
/// added/removed/retargeted) — regenerated byte-for-byte, so an unchanged grant line stays diff-clean;
/// and upgrade tier costs and effect value.amounts. Anything it cannot do surgically — a level added
/// or removed, an upgrade tier or effect added or removed, an effect field other than amount, creating
/// resources or stations — it **refuses loudly before writing a single byte**, rather than silently
/// dropping the edit. Fail loud, fail early, fail whole.
public sealed class AssetWriter
{
    private const string RecipeScriptFallbackGuid = "58c7e8d127a744f82866546ee5265bf2"; // RecipeSO
    private const string QuestScriptFallbackGuid = "3c9335b8e6a8345d2ae72fd9e7e239ee";  // QuestSO
    private static readonly Regex GuidLine = new(@"^guid:\s*([0-9a-fA-F]{32})", RegexOptions.Multiline);

    private readonly string _projectRoot;
    private readonly EconomyReader _reader;
    private readonly BalanceConfig _current;
    private readonly GuidIndex _guids;

    public AssetWriter(string projectRoot, EconomyReader reader, BalanceConfig current)
    {
        _projectRoot = projectRoot;
        _reader = reader;
        _current = current;
        _guids = reader.Guids;
    }

    // ---- Plan: validate everything, diff, and describe the changes. Writes nothing. ----

    public WritePlan Plan(BalanceConfig incoming)
    {
        if (incoming.SchemaVersion != BalanceConfig.CurrentSchemaVersion)
            throw new WriteRefusedException(
                $"schemaVersion mismatch: config declares {incoming.SchemaVersion}, tool supports {BalanceConfig.CurrentSchemaVersion}. Aborting; nothing written.");

        // Refuse in config-space anything the game would reject at boot (rules the economy sim doesn't model),
        // before a single .asset is touched — a valid diff to Unity must also be a bootable one.
        BootRules.Validate(incoming);

        var plan = new WritePlan();

        DiffGlobal(incoming, plan);
        DiffXp(incoming, plan);
        DiffOrders(incoming, plan);
        DiffResources(incoming, plan);
        DiffRecipes(incoming, plan);   // finds insertions
        DiffStations(incoming, plan);  // needs insertions resolved first (recipe wiring)
        DiffUpgrades(incoming, plan);  // unlockLevel + tier cost + effect value.amount
        DiffLevels(incoming, plan);    // xpThreshold + grant amounts + structural grant-block rewrites
        DiffQuests(incoming, plan);    // create / delete / reorder quests + scalar reward/goal/condition edits

        return plan;
    }

    // ---- Apply: perform the planned edits. Only reached with --apply. ----

    public void Apply(WritePlan plan)
    {
        foreach (var change in plan.Scalars)
            SetScalar(change);

        foreach (var insert in plan.RecipeInsertions)
            InsertRecipe(insert);

        if (plan.UpgradeEdits.Count > 0)
            ApplyUpgradeEdits(plan.UpgradeEdits);

        // Grant rewrites before scalar level edits: both touch the Levels asset, and a rewrite replaces a
        // whole grants block while a scalar edit finds its line by counting markers (shift-safe either way).
        if (plan.GrantRewrites.Count > 0)
            ApplyGrantRewrites(plan.GrantRewrites);

        if (plan.LevelEdits.Count > 0)
            ApplyLevelEdits(plan.LevelEdits);

        // Quests: create the new asset files, then rewrite the GameConfig.quests reference block (which carries
        // the new guids), then delete removed asset files, then apply scalar edits to surviving quest assets.
        // Each op re-reads the file it touches, so the GameConfig block rewrite and any GameConfig scalar edits
        // above don't collide (both locate their line independently).
        foreach (var insert in plan.QuestInsertions)
            InsertQuest(insert);

        if (plan.QuestBlockRewrite != null)
            ApplyQuestBlockRewrite(plan.QuestBlockRewrite);

        foreach (var del in plan.QuestDeletions)
            DeleteQuest(del);

        if (plan.QuestEdits.Count > 0)
            ApplyQuestEdits(plan.QuestEdits);
    }

    // ================= Diffing =================

    private void DiffGlobal(BalanceConfig inc, WritePlan plan)
    {
        var cur = _current.Global;
        var g = inc.Global;
        var path = EconomyReader.GameConfigPath;
        Scalar(plan, path, "gridCols", cur.GridCols, g.GridCols);
        Scalar(plan, path, "gridRows", cur.GridRows, g.GridRows);
        Scalar(plan, path, "cellSize", cur.CellSize, g.CellSize);
        Scalar(plan, path, "refundPercent", cur.RefundPercent, g.RefundPercent);
        Scalar(plan, path, "startingStorageCapacity", cur.StartingStorageCapacity, g.StartingStorageCapacity);
        // Gems are authored as top-level fields on GameConfig.asset (the schema groups them separately).
        Scalar(plan, path, "startingGems", _current.Gems.StartingGems, inc.Gems.StartingGems);
        Scalar(plan, path, "secondsPerGem", _current.Gems.SecondsPerGem, inc.Gems.SecondsPerGem);
        Scalar(plan, path, "minGemCost", _current.Gems.MinGemCost, inc.Gems.MinGemCost);

        if (!SameResourceQuantities(cur.StartingResources, g.StartingResources))
            throw Unsupported("Global.StartingResources", "editing the starting-resource list");
        if (!SameStartingStations(cur.StartingStations, g.StartingStations))
            throw Unsupported("Global.StartingStations", "these are scene-owned (Farm.unity), not tool-editable");
    }

    private void DiffXp(BalanceConfig inc, WritePlan plan)
    {
        var path = _reader.XpConfigPath;
        Scalar(plan, path, "perJobCollected", _current.Xp.PerJobCollected, inc.Xp.PerJobCollected);
        // perStationBuilt is absent from the asset (SO field initializer); allow appending it.
        Scalar(plan, path, "perStationBuilt", _current.Xp.PerStationBuilt, inc.Xp.PerStationBuilt, absentAllowed: true);
    }

    private void DiffOrders(BalanceConfig inc, WritePlan plan)
    {
        var path = _reader.OrderConfigPath;
        var c = _current.Orders;
        var o = inc.Orders;
        Scalar(plan, path, "slotCount", c.SlotCount, o.SlotCount);
        Scalar(plan, path, "refillSeconds", c.RefillSeconds, o.RefillSeconds);
        Scalar(plan, path, "minRequestKinds", c.MinRequestKinds, o.MinRequestKinds);
        Scalar(plan, path, "maxRequestKinds", c.MaxRequestKinds, o.MaxRequestKinds);
        Scalar(plan, path, "maxQuantityAtLevel1", c.MaxQuantityAtLevel1, o.MaxQuantityAtLevel1);
        Scalar(plan, path, "maxQuantityPerLevel", c.MaxQuantityPerLevel, o.MaxQuantityPerLevel);
        Scalar(plan, path, "tierWeightBase", c.TierWeightBase, o.TierWeightBase);
        Scalar(plan, path, "tierWeightPerLevel", c.TierWeightPerLevel, o.TierWeightPerLevel);
        Scalar(plan, path, "cashMultiplier", c.CashMultiplier, o.CashMultiplier);
        Scalar(plan, path, "xpMultiplier", c.XpMultiplier, o.XpMultiplier);
    }

    private void DiffResources(BalanceConfig inc, WritePlan plan)
    {
        var currentById = _current.Resources.ToDictionary(r => r.Id);
        var incomingIds = new HashSet<string>();

        foreach (var r in inc.Resources)
        {
            incomingIds.Add(r.Id);
            if (!currentById.TryGetValue(r.Id, out var cur))
                throw new WriteRefusedException(
                    $"resource id '{r.Id}' matches no asset. Creating resources is out of scope (they need icons/prefabs authored in Unity). Aborting; nothing written.");
            if (r.DisplayName != cur.DisplayName)
                throw Unsupported($"resource '{r.Id}'", "changing a resource displayName");

            var path = ResourcePath(r.Id);
            Scalar(plan, path, "baseValue", cur.BaseValue, r.BaseValue);
            Scalar(plan, path, "sellable", cur.Sellable, r.Sellable);
            Scalar(plan, path, "tier", cur.Tier, r.Tier);
        }

        foreach (var cur in _current.Resources)
            if (!incomingIds.Contains(cur.Id))
                throw Unsupported($"resource '{cur.Id}'", "deleting a resource");
    }

    private void DiffRecipes(BalanceConfig inc, WritePlan plan)
    {
        var currentById = _current.Recipes.ToDictionary(r => r.Id);
        var stationTypes = _current.Stations.Select(s => s.StationType).ToHashSet();
        var resourceIds = _current.Resources.Select(r => r.Id).ToHashSet();
        var incomingIds = new HashSet<string>();

        foreach (var r in inc.Recipes)
        {
            incomingIds.Add(r.Id);
            if (currentById.TryGetValue(r.Id, out var cur))
            {
                if (r.StationType != cur.StationType)
                    throw Unsupported($"recipe '{r.Id}'", "re-homing a recipe to a different station");
                if (!SameResourceQuantities(cur.Inputs, r.Inputs) || !SameResourceQuantities(cur.Outputs, r.Outputs))
                    throw Unsupported($"recipe '{r.Id}'", "editing recipe inputs/outputs");
                Scalar(plan, RecipePath(r.Id), "duration", cur.Duration, r.Duration);
                // unlockLevel post-dates most recipe assets (added by Feature A) — append it when absent.
                Scalar(plan, RecipePath(r.Id), "unlockLevel", cur.UnlockLevel, r.UnlockLevel, absentAllowed: true);
            }
            else
            {
                // New recipe → structural insertion. Validate its references exist first.
                if (!stationTypes.Contains(r.StationType))
                    throw new WriteRefusedException(
                        $"new recipe '{r.Id}' targets station '{r.StationType}', which matches no asset. Aborting; nothing written.");
                foreach (var q in r.Inputs.Concat(r.Outputs))
                    if (!resourceIds.Contains(q.Resource))
                        throw new WriteRefusedException(
                            $"new recipe '{r.Id}' references resource '{q.Resource}', which matches no asset. Aborting; nothing written.");
                plan.RecipeInsertions.Add(new RecipeInsertion(r));
            }
        }

        foreach (var cur in _current.Recipes)
            if (!incomingIds.Contains(cur.Id))
                throw Unsupported($"recipe '{cur.Id}'", "deleting a recipe");
    }

    private void DiffStations(BalanceConfig inc, WritePlan plan)
    {
        var currentByType = _current.Stations.ToDictionary(s => s.StationType);
        var insertedByStation = plan.RecipeInsertions
            .GroupBy(i => i.Recipe.StationType)
            .ToDictionary(g => g.Key, g => g.Select(i => i.Recipe.Id).ToHashSet());

        foreach (var s in inc.Stations)
        {
            if (!currentByType.TryGetValue(s.StationType, out var cur))
                throw new WriteRefusedException(
                    $"station '{s.StationType}' matches no asset. Creating stations is out of scope. Aborting; nothing written.");
            if (s.DisplayName != cur.DisplayName)
                throw Unsupported($"station '{s.StationType}'", "changing a station displayName");

            var path = StationPath(s.StationType);
            Scalar(plan, path, "buildable", cur.Buildable, s.Buildable);
            Scalar(plan, path, "buildCost", cur.BuildCost, s.BuildCost);
            Scalar(plan, path, "cap", cur.Cap, s.Cap);
            Scalar(plan, path, "unlockLevel", cur.UnlockLevel, s.UnlockLevel);
            Scalar(plan, path, "queueDepth", cur.QueueDepth, s.QueueDepth);
            Scalar(plan, path, "width", cur.Width, s.Width);
            Scalar(plan, path, "height", cur.Height, s.Height);
            Scalar(plan, path, "buildSeconds", cur.BuildSeconds, s.BuildSeconds, absentAllowed: true);

            var allowedExtra = insertedByStation.GetValueOrDefault(s.StationType) ?? new HashSet<string>();
            VerifyIdListDelta(s.StationType, "recipes", cur.RecipeIds, s.RecipeIds, allowedExtra);
            VerifyIdListDelta(s.StationType, "upgrades", cur.UpgradeIds, s.UpgradeIds, new HashSet<string>());
        }

        foreach (var cur in _current.Stations)
            if (inc.Stations.All(s => s.StationType != cur.StationType))
                throw Unsupported($"station '{cur.StationType}'", "deleting a station");
    }

    // The only permitted difference between the current and incoming id list is the appearance of a
    // recipe this run is inserting. A removal, or any other addition, is an unsupported rewire.
    private void VerifyIdListDelta(string stationType, string field,
        List<string> current, List<string> incoming, HashSet<string> allowedExtra)
    {
        var cur = current.ToHashSet();
        var inc = incoming.ToHashSet();
        foreach (var removed in cur.Where(id => !inc.Contains(id)))
            throw Unsupported($"station '{stationType}'", $"removing '{removed}' from {field}");
        foreach (var added in inc.Where(id => !cur.Contains(id)))
            if (!allowedExtra.Contains(added))
                throw Unsupported($"station '{stationType}'",
                    $"adding '{added}' to {field} (not a recipe being inserted this run)");
    }

    // Upgrade unlockLevel is a top-level scalar on the UpgradeSO — line-addressable like any other. Tier costs
    // and effect value.amounts are line-addressable scalars too (positionally located, like the Levels asset),
    // so they are diffed as movable knobs. Structural tier/effect change (add/remove) or any non-amount effect
    // field has no surgical path and is still refused loud.
    private void DiffUpgrades(BalanceConfig inc, WritePlan plan)
    {
        var currentById = _current.Upgrades.ToDictionary(u => u.Id);
        var incomingIds = new HashSet<string>();

        foreach (var u in inc.Upgrades)
        {
            incomingIds.Add(u.Id);
            if (!currentById.TryGetValue(u.Id, out var cur))
                throw new WriteRefusedException(
                    $"upgrade id '{u.Id}' matches no asset. Creating upgrades is out of scope. Aborting; nothing written.");
            if (u.DisplayName != cur.DisplayName)
                throw Unsupported($"upgrade '{u.Id}'", "changing an upgrade displayName");
            Scalar(plan, UpgradePath(u.Id), "unlockLevel", cur.UnlockLevel, u.UnlockLevel, absentAllowed: true);
            DiffUpgradeTiers(UpgradePath(u.Id), u.Id, cur.Tiers, u.Tiers, plan);
        }

        foreach (var cur in _current.Upgrades)
            if (!incomingIds.Contains(cur.Id))
                throw Unsupported($"upgrade '{cur.Id}'", "deleting an upgrade");
    }

    private void DiffUpgradeTiers(string path, string upgradeId,
        List<UpgradeTierConfig> cur, List<UpgradeTierConfig> inc, WritePlan plan)
    {
        if (cur.Count != inc.Count)
            throw Unsupported($"upgrade '{upgradeId}'", "adding or removing an upgrade tier");

        for (int t = 0; t < cur.Count; t++)
        {
            if (cur[t].Cost != inc[t].Cost)
                plan.UpgradeEdits.Add(new UpgradeEdit(path, t, null,
                    cur[t].Cost.ToString(CultureInfo.InvariantCulture),
                    inc[t].Cost.ToString(CultureInfo.InvariantCulture)));

            var ce = cur[t].Effects;
            var ie = inc[t].Effects;
            if (ce.Count != ie.Count)
                throw Unsupported($"upgrade '{upgradeId}' tier {t + 1}", "adding or removing an effect");

            for (int e = 0; e < ce.Count; e++)
            {
                if (EffectDiffersBeyondAmount(ce[e], ie[e]))
                    throw Unsupported($"upgrade '{upgradeId}' tier {t + 1} effect {e + 1}",
                        "editing an effect field other than amount");
                if (ce[e].Amount != ie[e].Amount)
                    plan.UpgradeEdits.Add(new UpgradeEdit(path, t, e,
                        FormatFloat(ce[e].Amount), FormatFloat(ie[e].Amount)));
            }
        }
    }

    // The Levels asset is a single SO holding a list of level entries, each with a nested grant list. A level's
    // xpThreshold and a grant's amount are movable scalars, addressed positionally. When a level's grant list
    // changes STRUCTURALLY (a grant added, removed, or retargeted to a new kind/station), there is no per-scalar
    // path, so that level's whole grant block is regenerated from config — byte-for-byte to Unity's own layout,
    // so an unchanged grant line reproduces identically and the git diff stays minimal. Adding or removing a
    // whole level still has no surgical path and is refused loud. Applied by ApplyLevelEdits / ApplyGrantRewrites.
    private void DiffLevels(BalanceConfig inc, WritePlan plan)
    {
        if (inc.Levels.Count != _current.Levels.Count)
            throw Unsupported("Levels", "adding or removing a level");

        for (int i = 0; i < inc.Levels.Count; i++)
        {
            var cur = _current.Levels[i];
            var lv = inc.Levels[i];

            if (cur.XpThreshold != lv.XpThreshold)
                plan.LevelEdits.Add(new LevelEdit(i, null,
                    cur.XpThreshold.ToString(CultureInfo.InvariantCulture),
                    lv.XpThreshold.ToString(CultureInfo.InvariantCulture)));

            if (GrantsStructurallyDiffer(cur.Grants, lv.Grants))
                plan.GrantRewrites.Add(new LevelGrantsRewrite(i, BuildGrantsBlock(lv.Grants)));
            else
                for (int j = 0; j < cur.Grants.Count; j++)
                    if (cur.Grants[j].Amount != lv.Grants[j].Amount)
                        plan.LevelEdits.Add(new LevelEdit(i, j,
                            cur.Grants[j].Amount.ToString(CultureInfo.InvariantCulture),
                            lv.Grants[j].Amount.ToString(CultureInfo.InvariantCulture)));
        }
    }

    // Structural = a different number of grants, or the same slot carrying a different kind/target. An
    // amount-only delta is NOT structural (it stays a minimal per-grant scalar edit).
    private static bool GrantsStructurallyDiffer(List<LevelGrantConfig> a, List<LevelGrantConfig> b)
    {
        if (a.Count != b.Count) return true;
        for (int i = 0; i < a.Count; i++)
            if (a[i].Kind != b[i].Kind || a[i].TargetStation != b[i].TargetStation) return true;
        return false;
    }

    private static bool EffectDiffersBeyondAmount(EffectConfig a, EffectConfig b) =>
        a.Id != b.Id || a.Type != b.Type || a.Op != b.Op || a.Resource != b.Resource || a.Range != b.Range ||
        a.Trigger != b.Trigger || a.TriggerChance != b.TriggerChance || a.ConditionType != b.ConditionType ||
        a.ConditionArg != b.ConditionArg || a.ConditionAmount != b.ConditionAmount;

    // Regenerate a level's grant section exactly as Unity serialises it: `    grants: []` when empty, else a
    // `    grants:` line followed by a 3-line block per grant. A null target renders `{fileID: 0}`; a station
    // target renders its SO reference. Kind names map to the Core enum's integer index (append-only, per the
    // LevelEntryKind comment), so a name the enum does not define is refused loud rather than written as a guess.
    private List<string> BuildGrantsBlock(List<LevelGrantConfig> grants)
    {
        if (grants.Count == 0) return new List<string> { "    grants: []" };

        var block = new List<string> { "    grants:" };
        foreach (var g in grants)
        {
            if (!Enum.TryParse<LevelEntryKind>(g.Kind, ignoreCase: false, out var kind))
                throw new WriteRefusedException(
                    $"grant kind '{g.Kind}' is not a defined LevelEntryKind. Aborting; nothing written.");
            block.Add($"    - kind: {(int)kind}");
            block.Add($"      targetStation: {GrantTargetRef(g.TargetStation)}");
            block.Add($"      amount: {g.Amount}");
        }
        return block;
    }

    private string GrantTargetRef(string? stationType)
    {
        if (stationType == null) return "{fileID: 0}";
        if (_reader.StationGuidByType.TryGetValue(stationType, out var guid))
            return $"{{fileID: 11400000, guid: {guid}, type: 2}}";
        throw new WriteRefusedException(
            $"grant targetStation '{stationType}' matches no station asset. Aborting; nothing written.");
    }

    // ================= Quest diffing =================

    // Quests are the one collection that supports the full structural set (create / delete / reorder) as well as
    // scalar edits — the milestone's explicit requirement. An existing quest may only move its scalar knobs
    // (reward xp/money/gems, goal amount, condition amounts); any other change to it has no surgical path and is
    // refused loud. A quest present in the config but absent from Unity is a create; the reverse is a delete. The
    // GameConfig.quests reference list is regenerated byte-for-byte whenever membership or order changes (the
    // grant-block-rewrite template), so a create appends, a delete removes, and a reorder permutes — all one path.
    private void DiffQuests(BalanceConfig inc, WritePlan plan)
    {
        var currentById = _current.Quests.ToDictionary(q => q.Id);
        var resourceIds = _current.Resources.Select(r => r.Id).ToHashSet();
        var incomingIds = new HashSet<string>();
        var newGuidById = new Dictionary<string, string>();

        foreach (var q in inc.Quests)
        {
            if (!incomingIds.Add(q.Id))
                throw new WriteRefusedException($"duplicate quest id '{q.Id}' in the config. Aborting; nothing written.");

            if (currentById.TryGetValue(q.Id, out var cur))
            {
                if (!SameQuestStructure(cur, q))
                    throw Unsupported($"quest '{q.Id}'",
                        "editing its goal kind/target, conditions, or reward resources (only reward xp/money/gems, "
                        + "goal amount, and condition amounts are line-addressable scalars)");

                var path = QuestPath(q.Id);
                QuestScalar(plan, path, QuestField.RewardXp, null, cur.Reward.Xp, q.Reward.Xp);
                QuestScalar(plan, path, QuestField.RewardMoney, null, cur.Reward.Money, q.Reward.Money);
                QuestScalar(plan, path, QuestField.RewardGems, null, cur.Reward.Gems, q.Reward.Gems);
                QuestScalar(plan, path, QuestField.GoalAmount, null, cur.Goal.Amount, q.Goal.Amount);
                for (int i = 0; i < cur.Conditions.Count; i++)
                    QuestScalar(plan, path, QuestField.ConditionAmount, i, cur.Conditions[i].Amount, q.Conditions[i].Amount);
            }
            else
            {
                ValidateNewQuestReferences(q, resourceIds);
                var guid = Guid.NewGuid().ToString("N");
                newGuidById[q.Id] = guid;
                plan.QuestInsertions.Add(new QuestInsertion(q, guid));
            }
        }

        foreach (var cur in _current.Quests)
            if (!incomingIds.Contains(cur.Id))
            {
                var guid = _reader.QuestGuidById[cur.Id];
                plan.QuestDeletions.Add(new QuestDeletion(cur.Id, guid, _guids.PathFor(guid)));
            }

        // Regenerate the reference block only when the ordered guid list actually changes — a pure scalar edit
        // leaves it identical (so a round-trip plans nothing here).
        var desired = inc.Quests
            .Select(q => _reader.QuestGuidById.TryGetValue(q.Id, out var g) ? g : newGuidById[q.Id])
            .ToList();
        var currentGuids = _current.Quests.Select(q => _reader.QuestGuidById[q.Id]).ToList();
        if (!desired.SequenceEqual(currentGuids))
            plan.QuestBlockRewrite = BuildQuestsBlock(desired);
    }

    // An existing quest may only move scalar knobs; everything else (goal kind/target, the condition set, the
    // reward resource list) is a structural change with no surgical write path.
    private static bool SameQuestStructure(QuestConfig a, QuestConfig b)
    {
        if (a.Goal.Kind != b.Goal.Kind || a.Goal.TargetId != b.Goal.TargetId) return false;
        if (a.Conditions.Count != b.Conditions.Count) return false;
        for (int i = 0; i < a.Conditions.Count; i++)
            if (a.Conditions[i].Kind != b.Conditions[i].Kind || a.Conditions[i].Arg != b.Conditions[i].Arg) return false;
        return SameResourceQuantities(a.Reward.Resources, b.Reward.Resources);
    }

    // A new quest's enum kinds must be defined and its reward resources must resolve to real assets, before a
    // guid is allocated and the asset written. (Boot-rule checks — amount ranges, QuestCompleted cross-refs —
    // are enforced separately by BootRules.Validate over the whole incoming config.)
    private void ValidateNewQuestReferences(QuestConfig q, HashSet<string> resourceIds)
    {
        if (string.IsNullOrWhiteSpace(q.Id))
            throw new WriteRefusedException("a new quest has an empty id. Aborting; nothing written.");
        if (!Enum.TryParse<GoalKind>(q.Goal.Kind, ignoreCase: false, out _))
            throw new WriteRefusedException(
                $"new quest '{q.Id}' goal kind '{q.Goal.Kind}' is not a defined GoalKind. Aborting; nothing written.");
        foreach (var c in q.Conditions)
            if (!Enum.TryParse<ConditionKind>(c.Kind, ignoreCase: false, out _))
                throw new WriteRefusedException(
                    $"new quest '{q.Id}' condition kind '{c.Kind}' is not a defined ConditionKind. Aborting; nothing written.");
        foreach (var r in q.Reward.Resources)
            if (!resourceIds.Contains(r.Resource))
                throw new WriteRefusedException(
                    $"new quest '{q.Id}' reward references resource '{r.Resource}', which matches no asset. Aborting; nothing written.");
    }

    private static void QuestScalar(WritePlan plan, string path, QuestField field, int? condIndex, int oldV, int newV)
    {
        if (oldV != newV)
            plan.QuestEdits.Add(new QuestEdit(path, field, condIndex,
                oldV.ToString(CultureInfo.InvariantCulture), newV.ToString(CultureInfo.InvariantCulture)));
    }

    // The GameConfig.quests block: `  quests: []` when empty, else a `  quests:` header and one 2-space list
    // item per guid — the same shape ReadQuests reads back (roster order preserved).
    private static List<string> BuildQuestsBlock(List<string> guids)
    {
        if (guids.Count == 0) return new List<string> { "  quests: []" };
        var block = new List<string> { "  quests:" };
        foreach (var g in guids)
            block.Add($"  - {{fileID: 11400000, guid: {g}, type: 2}}");
        return block;
    }

    // ================= Structural insertion =================

    private void InsertQuest(QuestInsertion insert)
    {
        var q = insert.Quest;
        var name = "Quest_" + q.Id.Replace('.', '_');
        var relPath = $"Assets/Data/SO/{name}.asset";
        var absAsset = _guids.AbsolutePath(relPath);
        if (File.Exists(absAsset))
            throw new WriteRefusedException($"cannot create '{relPath}': a file already exists there.");

        File.WriteAllText(absAsset, BuildQuestAsset(name, ResolveQuestScriptGuid(), q));
        File.WriteAllText(absAsset + ".meta", BuildMeta(insert.Guid));
    }

    // Steal the QuestSO script guid from an existing quest asset so it can never drift from the project; fall
    // back to the known guid when no quest exists yet.
    private string ResolveQuestScriptGuid()
    {
        var sampleId = _current.Quests.FirstOrDefault()?.Id;
        if (sampleId == null) return QuestScriptFallbackGuid;
        var text = File.ReadAllText(_guids.AbsolutePath(QuestPath(sampleId)));
        var m = Regex.Match(text, @"m_Script:\s*\{fileID:\s*\d+,\s*guid:\s*([0-9a-fA-F]{32})");
        return m.Success ? m.Groups[1].Value : QuestScriptFallbackGuid;
    }

    // Serialise a QuestSO body exactly as Unity does (enum kinds as their integer index, empty strings as
    // `key: ` with a trailing space, empty lists as `[]`), so the created asset reimports without a rewrite.
    private string BuildQuestAsset(string name, string scriptGuid, QuestConfig q)
    {
        var sb = new StringBuilder();
        sb.Append("%YAML 1.1\n");
        sb.Append("%TAG !u! tag:unity3d.com,2011:\n");
        sb.Append("--- !u!114 &11400000\n");
        sb.Append("MonoBehaviour:\n");
        sb.Append("  m_ObjectHideFlags: 0\n");
        sb.Append("  m_CorrespondingSourceObject: {fileID: 0}\n");
        sb.Append("  m_PrefabInstance: {fileID: 0}\n");
        sb.Append("  m_PrefabAsset: {fileID: 0}\n");
        sb.Append("  m_GameObject: {fileID: 0}\n");
        sb.Append("  m_Enabled: 1\n");
        sb.Append("  m_EditorHideFlags: 0\n");
        sb.Append($"  m_Script: {{fileID: 11500000, guid: {scriptGuid}, type: 3}}\n");
        sb.Append($"  m_Name: {name}\n");
        sb.Append("  m_EditorClassIdentifier: Assembly-CSharp::VoidDay.Data.QuestSO\n");
        sb.Append($"  id: {q.Id}\n");
        AppendConditionsBlock(sb, q.Conditions);
        sb.Append("  goal:\n");
        sb.Append($"    kind: {(int)Enum.Parse<GoalKind>(q.Goal.Kind)}\n");
        sb.Append($"    amount: {q.Goal.Amount}\n");
        sb.Append($"    targetId: {q.Goal.TargetId}\n");
        sb.Append("  reward:\n");
        sb.Append($"    xp: {q.Reward.Xp}\n");
        sb.Append($"    money: {q.Reward.Money}\n");
        sb.Append($"    gems: {q.Reward.Gems}\n");
        AppendRewardResources(sb, q.Reward.Resources);
        return sb.ToString();
    }

    private static void AppendConditionsBlock(StringBuilder sb, List<QuestConditionConfig> conditions)
    {
        if (conditions.Count == 0) { sb.Append("  conditions: []\n"); return; }
        sb.Append("  conditions:\n");
        foreach (var c in conditions)
        {
            sb.Append($"  - kind: {(int)Enum.Parse<ConditionKind>(c.Kind)}\n");
            sb.Append($"    amount: {c.Amount}\n");
            sb.Append($"    arg: {c.Arg}\n");
        }
    }

    private void AppendRewardResources(StringBuilder sb, List<ResourceQuantity> resources)
    {
        if (resources.Count == 0) { sb.Append("    resources: []\n"); return; }
        sb.Append("    resources:\n");
        foreach (var r in resources)
        {
            var guid = _reader.ResourceGuidById[r.Resource];
            sb.Append($"    - resource: {{fileID: 11400000, guid: {guid}, type: 2}}\n");
            sb.Append($"      amount: {r.Amount}\n");
        }
    }

    // Replace the GameConfig.quests block (header + its 2-space list items) with the regenerated one. Handles
    // both the block form (`  quests:` + items) and the empty form (`  quests: []`, no items follow).
    private void ApplyQuestBlockRewrite(List<string> block)
    {
        var abs = _guids.AbsolutePath(EconomyReader.GameConfigPath);
        var lines = File.ReadAllText(abs).Replace("\r\n", "\n").Split('\n').ToList();

        int questsLine = lines.FindIndex(l => l == "  quests:" || l == "  quests: []");
        if (questsLine < 0)
            throw new WriteRefusedException(
                $"{EconomyReader.GameConfigPath}: no 'quests:' list to rewrite. Refusing to write.");

        int end = questsLine + 1;
        while (end < lines.Count && lines[end].StartsWith("  - ")) end++;

        lines.RemoveRange(questsLine, end - questsLine);
        lines.InsertRange(questsLine, block);
        File.WriteAllText(abs, string.Join('\n', lines));
    }

    private void DeleteQuest(QuestDeletion del)
    {
        var abs = _guids.AbsolutePath(del.AssetPath);
        if (File.Exists(abs)) File.Delete(abs);
        if (File.Exists(abs + ".meta")) File.Delete(abs + ".meta");
    }

    // Quest scalar edits are nested (reward.xp is a 4-space field under a 2-space `reward:` header), so they use
    // positional finders like the Levels/Upgrade editors rather than the flat top-level SetScalar.
    private void ApplyQuestEdits(List<QuestEdit> edits)
    {
        foreach (var group in edits.GroupBy(e => e.AssetPath))
        {
            var abs = _guids.AbsolutePath(group.Key);
            var lines = File.ReadAllText(abs).Replace("\r\n", "\n").Split('\n').ToList();

            foreach (var edit in group)
            {
                int lineNo = FindQuestScalarLine(lines, edit, group.Key);
                ReplaceScalarValue(lines, lineNo, edit.Old, edit.New, group.Key);
            }

            File.WriteAllText(abs, string.Join('\n', lines));
        }
    }

    private int FindQuestScalarLine(List<string> lines, QuestEdit edit, string assetPath) => edit.Field switch
    {
        QuestField.RewardXp => FindNestedScalar(lines, "  reward:", "    xp:", assetPath),
        QuestField.RewardMoney => FindNestedScalar(lines, "  reward:", "    money:", assetPath),
        QuestField.RewardGems => FindNestedScalar(lines, "  reward:", "    gems:", assetPath),
        QuestField.GoalAmount => FindNestedScalar(lines, "  goal:", "    amount:", assetPath),
        QuestField.ConditionAmount => FindConditionAmountLine(lines, edit.ConditionIndex!.Value, assetPath),
        _ => throw new WriteRefusedException($"{assetPath}: unknown quest field {edit.Field}.")
    };

    // Find `fieldPrefix` under its `header` section, stopping at the next top-level (2-space) key so a field of
    // the same name in another section can't be matched.
    private static int FindNestedScalar(List<string> lines, string header, string fieldPrefix, string assetPath)
    {
        int h = lines.FindIndex(l => l == header);
        if (h < 0)
            throw new WriteRefusedException($"{assetPath}: no '{header.Trim()}' block. Refusing to guess.");
        for (int i = h + 1; i < lines.Count; i++)
        {
            if (lines[i].StartsWith(fieldPrefix)) return i;
            if (IsTopLevelKey(lines[i])) break;
        }
        throw new WriteRefusedException(
            $"{assetPath}: '{header.Trim()}' has no '{fieldPrefix.Trim()}' line. Refusing to guess.");
    }

    private static int FindConditionAmountLine(List<string> lines, int condIndex, string assetPath)
    {
        int h = lines.FindIndex(l => l == "  conditions:");
        if (h < 0)
            throw new WriteRefusedException($"{assetPath}: no 'conditions:' block for a condition amount edit. Refusing to guess.");
        int seen = 0;
        for (int i = h + 1; i < lines.Count; i++)
        {
            if (IsTopLevelKey(lines[i])) break;              // reached goal:/reward: — condition not found
            if (!lines[i].StartsWith("  - kind:")) continue;
            if (seen == condIndex)
            {
                for (int j = i + 1; j < lines.Count; j++)
                {
                    if (lines[j].StartsWith("    amount:")) return j;
                    if (lines[j].StartsWith("  - ") || IsTopLevelKey(lines[j])) break;
                }
                break;
            }
            seen++;
        }
        throw new WriteRefusedException(
            $"{assetPath}: could not locate condition {condIndex + 1}'s amount line. Refusing to guess.");
    }

    // A top-level MonoBehaviour key is indented exactly two spaces and is not a list item (`  - …`).
    private static bool IsTopLevelKey(string line) =>
        line.Length >= 3 && line[0] == ' ' && line[1] == ' ' && line[2] != ' ' && line[2] != '-';

    // ================= Structural insertion =================

    private void InsertRecipe(RecipeInsertion insert)
    {
        var r = insert.Recipe;
        var guid = Guid.NewGuid().ToString("N");
        var name = "Recipe_" + r.Id.Replace('.', '_');
        var relPath = $"Assets/Data/SO/{name}.asset";
        var absAsset = _guids.AbsolutePath(relPath);
        if (File.Exists(absAsset))
            throw new WriteRefusedException($"cannot create '{relPath}': a file already exists there.");

        var scriptGuid = ResolveRecipeScriptGuid(r.StationType);
        File.WriteAllText(absAsset, BuildRecipeAsset(name, scriptGuid, r));
        File.WriteAllText(absAsset + ".meta", BuildMeta(guid));

        AppendRecipeReference(StationPath(r.StationType), guid);
    }

    private string ResolveRecipeScriptGuid(string stationType)
    {
        // Steal the RecipeSO script guid from an existing recipe so it can never drift from the
        // project. Prefer one on the same station; fall back to any recipe, then the known guid.
        var station = _current.Stations.First(s => s.StationType == stationType);
        var sampleId = station.RecipeIds.FirstOrDefault() ?? _current.Recipes.FirstOrDefault()?.Id;
        if (sampleId == null) return RecipeScriptFallbackGuid;

        var text = File.ReadAllText(_guids.AbsolutePath(RecipePath(sampleId)));
        var m = Regex.Match(text, @"m_Script:\s*\{fileID:\s*\d+,\s*guid:\s*([0-9a-fA-F]{32})");
        return m.Success ? m.Groups[1].Value : RecipeScriptFallbackGuid;
    }

    private string BuildRecipeAsset(string name, string scriptGuid, RecipeConfig r)
    {
        var sb = new StringBuilder();
        sb.Append("%YAML 1.1\n");
        sb.Append("%TAG !u! tag:unity3d.com,2011:\n");
        sb.Append("--- !u!114 &11400000\n");
        sb.Append("MonoBehaviour:\n");
        sb.Append("  m_ObjectHideFlags: 0\n");
        sb.Append("  m_CorrespondingSourceObject: {fileID: 0}\n");
        sb.Append("  m_PrefabInstance: {fileID: 0}\n");
        sb.Append("  m_PrefabAsset: {fileID: 0}\n");
        sb.Append("  m_GameObject: {fileID: 0}\n");
        sb.Append("  m_Enabled: 1\n");
        sb.Append("  m_EditorHideFlags: 0\n");
        sb.Append($"  m_Script: {{fileID: 11500000, guid: {scriptGuid}, type: 3}}\n");
        sb.Append($"  m_Name: {name}\n");
        sb.Append("  m_EditorClassIdentifier: Assembly-CSharp::VoidDay.Data.RecipeSO\n");
        sb.Append($"  id: {r.Id}\n");
        sb.Append($"  stationType: {r.StationType}\n");
        AppendIngredientBlock(sb, "inputs", r.Inputs);
        AppendIngredientBlock(sb, "outputs", r.Outputs);
        sb.Append($"  duration: {FormatFloat(r.Duration)}\n");
        // Omit when it equals the SO initializer (1), exactly as a hand-authored asset does.
        if (r.UnlockLevel != 1) sb.Append($"  unlockLevel: {r.UnlockLevel}\n");
        return sb.ToString();
    }

    private void AppendIngredientBlock(StringBuilder sb, string field, List<ResourceQuantity> items)
    {
        if (items.Count == 0)
        {
            sb.Append($"  {field}: []\n");
            return;
        }
        sb.Append($"  {field}:\n");
        foreach (var q in items)
        {
            var guid = _reader.ResourceGuidById[q.Resource];
            sb.Append($"  - resource: {{fileID: 11400000, guid: {guid}, type: 2}}\n");
            sb.Append($"    amount: {q.Amount}\n");
        }
    }

    private static string BuildMeta(string guid) =>
        "fileFormatVersion: 2\n" +
        $"guid: {guid}\n" +
        "NativeFormatImporter:\n" +
        "  externalObjects: {}\n" +
        "  mainObjectFileID: 11400000\n" +
        "  userData: \n" +
        "  assetBundleName: \n" +
        "  assetBundleVariant: \n";

    // Append `- {fileID: ..., guid: NEW, type: 2}` after the last item of the station's recipes list.
    private void AppendRecipeReference(string stationRelPath, string newGuid)
    {
        var abs = _guids.AbsolutePath(stationRelPath);
        var lines = File.ReadAllText(abs).Replace("\r\n", "\n").Split('\n').ToList();

        var recipesLine = lines.FindIndex(l => l == "  recipes:");
        if (recipesLine < 0)
            throw new WriteRefusedException(
                $"{stationRelPath}: no block-form 'recipes:' list to append to (an empty '[]' list is not supported).");

        // Walk to the end of the contiguous list items that follow.
        var insertAt = recipesLine + 1;
        while (insertAt < lines.Count && lines[insertAt].StartsWith("  - "))
            insertAt++;

        lines.Insert(insertAt, $"  - {{fileID: 11400000, guid: {newGuid}, type: 2}}");
        File.WriteAllText(abs, string.Join('\n', lines));
    }

    // ================= Positional level editing =================

    // The Levels asset has a fixed, machine-authored shape: a level entry opens with a `  - xpThreshold:` line
    // (2-space list item), and each grant opens with a `    - kind:` line (4-space) carrying an `      amount:`
    // line below it. We locate each target by counting those markers in document order and replace only the
    // scalar after the colon — no reserialize, so a one-field edit is a one-line diff, same as SetScalar.
    private void ApplyLevelEdits(List<LevelEdit> edits)
    {
        var abs = _guids.AbsolutePath(_reader.LevelsPath);
        var lines = File.ReadAllText(abs).Replace("\r\n", "\n").Split('\n').ToList();

        foreach (var edit in edits)
        {
            int lineNo = edit.GrantIndex is int gi
                ? FindGrantAmountLine(lines, edit.LevelIndex, gi)
                : FindLevelXpLine(lines, edit.LevelIndex);
            ReplaceScalarValue(lines, lineNo, edit.Old, edit.New, _reader.LevelsPath);
        }

        File.WriteAllText(abs, string.Join('\n', lines));
    }

    // Replace each structurally-changed level's grant section with its regenerated block. Highest level index
    // first, so replacing a lower-in-file block never shifts the marker search for a level above it. The block
    // spans the `    grants:` line and every 4-/6-space grant line under it, up to the next level marker or EOF.
    private void ApplyGrantRewrites(List<LevelGrantsRewrite> rewrites)
    {
        var abs = _guids.AbsolutePath(_reader.LevelsPath);
        var lines = File.ReadAllText(abs).Replace("\r\n", "\n").Split('\n').ToList();

        foreach (var rw in rewrites.OrderByDescending(r => r.LevelIndex))
        {
            int grantsLine = FindLevelXpLine(lines, rw.LevelIndex) + 1;
            if (grantsLine >= lines.Count || !lines[grantsLine].StartsWith("    grants"))
                throw new WriteRefusedException(
                    $"{_reader.LevelsPath}: level {rw.LevelIndex + 1} has no 'grants:' line where expected. Refusing to write.");

            int end = grantsLine + 1;
            while (end < lines.Count && (lines[end].StartsWith("    - ") || lines[end].StartsWith("      "))) end++;

            lines.RemoveRange(grantsLine, end - grantsLine);
            lines.InsertRange(grantsLine, rw.Block);
        }

        File.WriteAllText(abs, string.Join('\n', lines));
    }

    // ================= Positional upgrade editing =================

    // Tier cost and effect value.amount are line scalars inside the UpgradeSO, located positionally: a tier opens
    // with `  - cost:` (2-space), an effect with `    - id:` (4-space), and the effect's value block carries an
    // `        amount:` (8-space) after its `      value:` header — distinct from the condition's amount below it.
    private void ApplyUpgradeEdits(List<UpgradeEdit> edits)
    {
        foreach (var group in edits.GroupBy(e => e.AssetPath))
        {
            var abs = _guids.AbsolutePath(group.Key);
            var lines = File.ReadAllText(abs).Replace("\r\n", "\n").Split('\n').ToList();

            foreach (var edit in group)
            {
                int lineNo = edit.EffectIndex is int ei
                    ? FindEffectAmountLine(lines, edit.TierIndex, ei, group.Key)
                    : FindTierCostLine(lines, edit.TierIndex, group.Key);
                ReplaceScalarValue(lines, lineNo, edit.Old, edit.New, group.Key);
            }

            File.WriteAllText(abs, string.Join('\n', lines));
        }
    }

    // The line index of the (tierIndex)-th `  - cost:` marker.
    private int FindTierCostLine(List<string> lines, int tierIndex, string assetPath)
    {
        int seen = 0;
        for (int i = 0; i < lines.Count; i++)
        {
            if (!lines[i].StartsWith("  - cost:")) continue;
            if (seen == tierIndex) return i;
            seen++;
        }
        throw new WriteRefusedException(
            $"{assetPath}: could not locate tier {tierIndex + 1}'s cost line. Refusing to guess.");
    }

    // The value.amount line of the (effectIndex)-th effect inside the (tierIndex)-th tier: the first
    // `        amount:` after that effect's `      value:` header (the condition's amount comes later).
    private int FindEffectAmountLine(List<string> lines, int tierIndex, int effectIndex, string assetPath)
    {
        int start = FindTierCostLine(lines, tierIndex, assetPath) + 1;
        int effectSeen = 0;
        for (int i = start; i < lines.Count; i++)
        {
            if (lines[i].StartsWith("  - cost:")) break; // next tier — effect not found
            if (!lines[i].StartsWith("    - id:")) continue;
            if (effectSeen == effectIndex)
            {
                bool inValue = false;
                for (int j = i + 1; j < lines.Count; j++)
                {
                    if (lines[j].StartsWith("    - id:") || lines[j].StartsWith("  - cost:")) break; // ran past
                    if (lines[j].StartsWith("      value:")) inValue = true;
                    else if (inValue && lines[j].StartsWith("        amount:")) return j;
                }
                break;
            }
            effectSeen++;
        }
        throw new WriteRefusedException(
            $"{assetPath}: could not locate tier {tierIndex + 1} effect {effectIndex + 1}'s value.amount line. Refusing to guess.");
    }

    // The line index of the (levelIndex)-th `  - xpThreshold:` marker.
    private int FindLevelXpLine(List<string> lines, int levelIndex)
    {
        int seen = 0;
        for (int i = 0; i < lines.Count; i++)
        {
            if (!lines[i].StartsWith("  - xpThreshold:")) continue;
            if (seen == levelIndex) return i;
            seen++;
        }
        throw new WriteRefusedException(
            $"{_reader.LevelsPath}: could not locate level {levelIndex + 1}'s xpThreshold line. Refusing to guess.");
    }

    // The `      amount:` line of the (grantIndex)-th grant inside the (levelIndex)-th level.
    private int FindGrantAmountLine(List<string> lines, int levelIndex, int grantIndex)
    {
        int start = FindLevelXpLine(lines, levelIndex) + 1;
        int grantSeen = 0;
        for (int i = start; i < lines.Count; i++)
        {
            if (lines[i].StartsWith("  - xpThreshold:")) break; // next level — grant not found
            if (!lines[i].StartsWith("    - kind:")) continue;
            if (grantSeen == grantIndex)
            {
                for (int j = i + 1; j < lines.Count; j++)
                {
                    if (lines[j].StartsWith("      amount:")) return j;
                    if (lines[j].StartsWith("    - ") || lines[j].StartsWith("  - ")) break; // ran past the grant
                }
                break;
            }
            grantSeen++;
        }
        throw new WriteRefusedException(
            $"{_reader.LevelsPath}: could not locate level {levelIndex + 1} grant {grantIndex + 1}'s amount line. Refusing to guess.");
    }

    // Swap the value after `key:` on one line, asserting it currently reads `expectedOld` — a drift guard so a
    // stale plan never silently rewrites the wrong number.
    private static void ReplaceScalarValue(List<string> lines, int lineNo, string expectedOld, string newValue, string assetPath)
    {
        var line = lines[lineNo];
        int colon = line.IndexOf(':');
        string current = line[(colon + 1)..].Trim();
        if (current != expectedOld)
            throw new WriteRefusedException(
                $"{assetPath}: line {lineNo + 1} reads '{current}', expected '{expectedOld}'. The asset changed under the plan; refusing to write.");
        lines[lineNo] = line[..(colon + 1)] + " " + newValue;
    }

    // ================= Scalar line editing =================

    private void Scalar(WritePlan plan, string assetPath, string field, int oldV, int newV)
    {
        if (oldV != newV)
            plan.Scalars.Add(new ScalarChange(assetPath, field, oldV.ToString(CultureInfo.InvariantCulture),
                newV.ToString(CultureInfo.InvariantCulture), false));
    }

    private void Scalar(WritePlan plan, string assetPath, string field, bool oldV, bool newV)
    {
        if (oldV != newV)
            plan.Scalars.Add(new ScalarChange(assetPath, field, oldV ? "1" : "0", newV ? "1" : "0", false));
    }

    private void Scalar(WritePlan plan, string assetPath, string field, float oldV, float newV, bool absentAllowed = false)
    {
        if (oldV != newV)
            plan.Scalars.Add(new ScalarChange(assetPath, field, FormatFloat(oldV), FormatFloat(newV), absentAllowed));
    }

    private void Scalar(WritePlan plan, string assetPath, string field, int oldV, int newV, bool absentAllowed)
    {
        if (oldV != newV)
            plan.Scalars.Add(new ScalarChange(assetPath, field, oldV.ToString(CultureInfo.InvariantCulture),
                newV.ToString(CultureInfo.InvariantCulture), absentAllowed));
    }

    private void SetScalar(ScalarChange change)
    {
        var abs = _guids.AbsolutePath(change.AssetPath);
        var lines = File.ReadAllText(abs).Replace("\r\n", "\n").Split('\n').ToList();

        // Top-level MonoBehaviour fields are indented exactly two spaces. Match on that to avoid
        // colliding with a nested field of the same name.
        var prefix = "  " + change.Field + ":";
        var matches = lines.Select((l, i) => (l, i)).Where(t => t.l.StartsWith(prefix)).ToList();

        if (matches.Count == 1)
        {
            lines[matches[0].i] = $"  {change.Field}: {change.New}";
        }
        else if (matches.Count == 0 && change.AbsentAllowed)
        {
            // Field absent from the asset (it post-dates it; the game applies the SO field
            // initializer). Unity reads SO fields by name, order-independent, so appending one line
            // at the end of the document body is a valid, minimal, one-line diff.
            InsertBeforeTrailingBlank(lines, $"  {change.Field}: {change.New}");
        }
        else
        {
            throw new WriteRefusedException(
                $"{change.AssetPath}: expected exactly one top-level '{change.Field}:' line, found {matches.Count}. Refusing to guess.");
        }

        File.WriteAllText(abs, string.Join('\n', lines));
    }

    private static void InsertBeforeTrailingBlank(List<string> lines, string newLine)
    {
        // Files end with a trailing newline, so Split leaves a final empty element. Insert before it.
        var at = lines.Count;
        while (at > 0 && lines[at - 1].Length == 0) at--;
        lines.Insert(at, newLine);
    }

    // ================= Path resolution =================

    private string RecipePath(string id) => _guids.PathFor(_reader.RecipeGuidById[id]);
    private string ResourcePath(string id) => _guids.PathFor(_reader.ResourceGuidById[id]);
    private string StationPath(string type) => _guids.PathFor(_reader.StationGuidByType[type]);
    private string UpgradePath(string id) => _guids.PathFor(_reader.UpgradeGuidById[id]);
    private string QuestPath(string id) => _guids.PathFor(_reader.QuestGuidById[id]);

    // ================= Equality helpers (order-sensitive for lists, as authored) =================

    private static bool SameResourceQuantities(List<ResourceQuantity> a, List<ResourceQuantity> b)
    {
        if (a.Count != b.Count) return false;
        for (var i = 0; i < a.Count; i++)
            if (a[i].Resource != b[i].Resource || a[i].Amount != b[i].Amount) return false;
        return true;
    }

    private static bool SameStartingStations(List<StartingStation> a, List<StartingStation> b)
    {
        if (a.Count != b.Count) return false;
        for (var i = 0; i < a.Count; i++)
            if (a[i].StationType != b[i].StationType || a[i].Count != b[i].Count) return false;
        return true;
    }

    // Unity writes whole floats without a decimal (`cellSize: 1`, `secondsPerGem: 30`) and others as
    // their shortest round-trippable form (`0.25`, `1.5`). Match that so an edited value reads back
    // identically and a diff shows exactly what changed.
    private static string FormatFloat(float f)
    {
        if (float.IsFinite(f) && MathF.Floor(f) == f)
            return ((long)f).ToString(CultureInfo.InvariantCulture);
        return f.ToString("R", CultureInfo.InvariantCulture);
    }

    private static WriteRefusedException Unsupported(string where, string what) =>
        new($"{where}: {what} is not supported by the M2 writer (no surgical write path). Aborting; nothing written.");
}

public sealed class WritePlan
{
    public List<ScalarChange> Scalars { get; } = new();
    public List<RecipeInsertion> RecipeInsertions { get; } = new();
    public List<LevelEdit> LevelEdits { get; } = new();
    public List<LevelGrantsRewrite> GrantRewrites { get; } = new();
    public List<UpgradeEdit> UpgradeEdits { get; } = new();
    public List<QuestInsertion> QuestInsertions { get; } = new();
    public List<QuestDeletion> QuestDeletions { get; } = new();
    public List<QuestEdit> QuestEdits { get; } = new();
    public List<string>? QuestBlockRewrite { get; set; }   // regenerated GameConfig.quests block, or null
    public bool IsEmpty => Scalars.Count == 0 && RecipeInsertions.Count == 0 && LevelEdits.Count == 0
        && GrantRewrites.Count == 0 && UpgradeEdits.Count == 0
        && QuestInsertions.Count == 0 && QuestDeletions.Count == 0 && QuestEdits.Count == 0
        && QuestBlockRewrite == null;
}

/// A quest scalar knob location inside a QuestSO asset (the only per-quest fields with a surgical write path).
public enum QuestField { RewardXp, RewardMoney, RewardGems, GoalAmount, ConditionAmount }

/// One scalar edit inside a QuestSO asset: a reward/goal amount (ConditionIndex == null) or the Nth condition's amount.
public readonly record struct QuestEdit(string AssetPath, QuestField Field, int? ConditionIndex, string Old, string New);

/// A new quest to create: its config plus the freshly-allocated guid wired into GameConfig.quests.
public sealed class QuestInsertion
{
    public QuestConfig Quest { get; }
    public string Guid { get; }
    public QuestInsertion(QuestConfig quest, string guid) { Quest = quest; Guid = guid; }
}

/// A quest to remove: unwired from GameConfig.quests (block rewrite) and its .asset + .meta deleted.
public readonly record struct QuestDeletion(string Id, string Guid, string AssetPath);

public readonly record struct ScalarChange(string AssetPath, string Field, string Old, string New, bool AbsentAllowed);

/// One positional edit inside the Levels asset: a level's xpThreshold (GrantIndex == null) or a grant's amount.
public readonly record struct LevelEdit(int LevelIndex, int? GrantIndex, string Old, string New);

/// A full regeneration of one level's grant section (used when its grants change structurally). Block holds the
/// replacement lines, from the `    grants:` line down.
public readonly record struct LevelGrantsRewrite(int LevelIndex, List<string> Block);

/// One positional scalar edit inside an UpgradeSO: a tier's cost (EffectIndex == null) or an effect's value.amount.
public readonly record struct UpgradeEdit(string AssetPath, int TierIndex, int? EffectIndex, string Old, string New);

public sealed class RecipeInsertion
{
    public RecipeConfig Recipe { get; }
    public RecipeInsertion(RecipeConfig recipe) => Recipe = recipe;
}

/// A validation refusal — a clean, named abort raised before any file is touched. Program prints its
/// message and exits non-zero; it is not a bug, so it does not warrant a stack trace.
public sealed class WriteRefusedException : Exception
{
    public WriteRefusedException(string message) : base(message) { }
}
